<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>sparrow-bom</artifactId>
        <groupId>com.sparrowzoo</groupId>
        <version>1.0.5-SNAPSHOT</version>
        <relativePath/>
    </parent>
    <packaging>pom</packaging>
    <artifactId>passport-bom</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <groupId>com.sparrowzoo.passport</groupId>
    <properties>
        <passport_version>1.0.0-SNAPSHOT</passport_version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.sparrowzoo.passport</groupId>
                <artifactId>passport-protocol</artifactId>
                <version>${passport_version}</version>
            </dependency>
            <dependency>
                <groupId>com.sparrowzoo.passport</groupId>
                <artifactId>passport-api</artifactId>
                <version>${passport_version}</version>
            </dependency>
            <dependency>
                <groupId>com.sparrowzoo.passport</groupId>
                <artifactId>passport-dao-api</artifactId>
                <version>${passport_version}</version>
            </dependency>
            <dependency>
                <groupId>com.sparrowzoo.passport</groupId>
                <artifactId>passport-sparrow-dao</artifactId>
                <version>${passport_version}</version>
            </dependency>
            <dependency>
                <groupId>com.sparrowzoo.passport</groupId>
                <artifactId>passport-mybatis</artifactId>
                <version>${passport_version}</version>
            </dependency>
            <dependency>
                <groupId>com.sparrowzoo.passport</groupId>
                <artifactId>passport-mybatis-plus</artifactId>
                <version>${passport_version}</version>
            </dependency>

            <dependency>
                <groupId>com.sparrowzoo.passport</groupId>
                <artifactId>passport-domain</artifactId>
                <version>${passport_version}</version>
            </dependency>

            <dependency>
                <groupId>com.sparrowzoo.passport</groupId>
                <artifactId>passport-application</artifactId>
                <version>${passport_version}</version>
            </dependency>

            <dependency>
                <groupId>com.sparrowzoo.passport</groupId>
                <artifactId>passport-starter</artifactId>
                <version>${passport_version}</version>
            </dependency>
            <dependency>
                <groupId>com.sparrowzoo.passport</groupId>
                <artifactId>passport-infrastructure</artifactId>
                <version>${passport_version}</version>
            </dependency>
            <dependency>
                <groupId>com.sparrowzoo.passport</groupId>
                <artifactId>passport-adapter</artifactId>
                <version>${passport_version}</version>
            </dependency>
            <dependency>
                <groupId>com.sparrowzoo.passport</groupId>
                <artifactId>passport-main-webapp</artifactId>
                <version>${passport_version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <url>http://maven.apache.org</url>
</project>
